# Generated by Django 6.0.3 on 2026-03-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('clinician', 'Clinician / Doctor'), ('hcc_staff', 'PHC Staff'), ('hcc_admin', 'PHC Admin'), ('fhc_staff', 'FMC Staff'), ('fhc_admin', 'FMC Admin'), ('admin', 'Platform Admin')], db_index=True, default='patient', max_length=20),
        ),
    ]
