# Generated by Django 6.0.3 on 2026-03-16 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalHealthCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='Short identifier e.g. FHC-ABJ-001', max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, help_text='Geopolitical zone', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Verification')], default='active', max_length=15)),
                ('notify_on_very_severe', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(blank=True, limit_choices_to={'role': 'fhc_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_fhc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Federal Health Center',
                'verbose_name_plural': 'Federal Health Centers',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthCareCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='Short identifier e.g. LGH-001', max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('lga', models.CharField(blank=True, max_length=100, verbose_name='LGA')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Verification')], default='active', max_length=15)),
                ('notify_on_severe', models.BooleanField(default=True)),
                ('notify_on_very_severe', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(blank=True, limit_choices_to={'role': 'hcc_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hcc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Care Center',
                'verbose_name_plural': 'Health Care Centers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(choices=[('general_practice', 'General Practice'), ('obstetrics_gynae', 'Obstetrics & Gynaecology'), ('endocrinology', 'Endocrinology'), ('cardiology', 'Cardiology'), ('internal_medicine', 'Internal Medicine'), ('reproductive_health', 'Reproductive Health'), ('midwifery', 'Midwifery'), ('nursing', 'Nursing'), ('other', 'Other')], default='general_practice', max_length=30)),
                ('license_number', models.CharField(blank=True, help_text='MDCN or relevant body license number', max_length=50)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('center_type', models.CharField(choices=[('hcc', 'Health Care Center'), ('fhc', 'Federal Health Center')], max_length=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='clinicians/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL)),
                ('fhc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicians', to='centers.federalhealthcenter')),
                ('hcc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicians', to='centers.healthcarecenter')),
            ],
            options={
                'verbose_name': 'Clinician Profile',
            },
        ),
    ]
