# Generated by Django 6.0.3 on 2026-03-18 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federalhealthcenter',
            options={'ordering': ['state', 'name'], 'verbose_name': 'Federal Medical Centre (FMC)', 'verbose_name_plural': 'Federal Medical Centres (FMC)'},
        ),
        migrations.AlterModelOptions(
            name='healthcarecenter',
            options={'ordering': ['state', 'name'], 'verbose_name': 'Primary Health Centre (PHC)', 'verbose_name_plural': 'Primary Health Centres (PHC)'},
        ),
        migrations.RemoveField(
            model_name='clinicianprofile',
            name='center_type',
        ),
        migrations.RemoveField(
            model_name='clinicianprofile',
            name='hcc',
        ),
        migrations.AddField(
            model_name='healthcarecenter',
            name='escalates_to',
            field=models.ForeignKey(blank=True, help_text='The FMC this PHC escalates Severe/Very Severe patients to. Set by Platform Admin only. Choose an FMC in the same state. If not set, system falls back to any active FMC in same state.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referring_phcs', to='centers.federalhealthcenter'),
        ),
        migrations.AlterField(
            model_name='clinicianprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='federalhealthcenter',
            name='code',
            field=models.CharField(help_text='e.g. FMC-ABJ-001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='federalhealthcenter',
            name='notify_on_very_severe',
            field=models.BooleanField(default=True, editable=False, help_text='Always True — FMC always receives Very Severe alerts.'),
        ),
        migrations.AlterField(
            model_name='federalhealthcenter',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='healthcarecenter',
            name='admin_user',
            field=models.OneToOneField(blank=True, help_text='The PHC Admin account that manages this facility.', limit_choices_to={'role': 'hcc_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthcarecenter',
            name='code',
            field=models.CharField(help_text='Short identifier e.g. PHC-LGS-001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcarecenter',
            name='lga',
            field=models.CharField(blank=True, help_text='Local Government Area. Used for proximity filtering.', max_length=100, verbose_name='LGA'),
        ),
        migrations.AlterField(
            model_name='healthcarecenter',
            name='notify_on_severe',
            field=models.BooleanField(default=True, help_text='Notify PHC admin/staff when a registered patient reaches Severe risk.'),
        ),
        migrations.AlterField(
            model_name='healthcarecenter',
            name='notify_on_very_severe',
            field=models.BooleanField(default=True, help_text='Notify PHC admin/staff when a registered patient reaches Very Severe risk.'),
        ),
        migrations.AlterField(
            model_name='healthcarecenter',
            name='state',
            field=models.CharField(blank=True, db_index=True, help_text='Nigerian state. Used for fallback FMC matching.', max_length=100),
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('change_phc', 'Change Home PHC'), ('report_issue', 'Report an Issue'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('description', models.TextField()),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_hcc', models.ForeignKey(blank=True, help_text='The PHC the patient wants to switch to (CHANGE_PHC only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_change_requests', to='centers.healthcarecenter')),
            ],
            options={
                'verbose_name': 'Change Request',
                'verbose_name_plural': 'Change Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FHCStaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_role', models.CharField(choices=[('coordinator', 'Case Coordinator'), ('triage', 'Triage Officer'), ('records', 'Records Officer'), ('other', 'Other')], default='other', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fhc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='centers.federalhealthcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fhc_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FMC Staff Profile',
            },
        ),
        migrations.CreateModel(
            name='HCCStaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_role', models.CharField(choices=[('nurse', 'Nurse'), ('cho', 'Community Health Officer'), ('assistant', 'Health Assistant'), ('receptionist', 'Receptionist'), ('other', 'Other')], default='other', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='centers.healthcarecenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hcc_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PHC Staff Profile',
            },
        ),
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('pcos', 'PCOS'), ('maternal', 'Maternal Health'), ('cardiovascular', 'Cardiovascular')], max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('very_severe', 'Very Severe')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open — Awaiting Assignment'), ('assigned', 'Assigned to Clinician'), ('under_treatment', 'Under Treatment'), ('discharged', 'Discharged')], db_index=True, default='open', max_length=20)),
                ('opening_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('closing_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fmc_notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(blank=True, help_text='Assigned by FMC staff. Null until assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='centers.clinicianprofile')),
                ('fhc', models.ForeignKey(blank=True, help_text='FMC handling this case. Set from PHC.escalates_to at creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='centers.federalhealthcenter')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FMC Patient Case',
                'verbose_name_plural': 'FMC Patient Cases',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PHCPatientRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('pcos', 'PCOS'), ('maternal', 'Maternal Health'), ('cardiovascular', 'Cardiovascular')], max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('very_severe', 'Very Severe')], help_text='Should only be mild or moderate at PHC level.', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New — Awaiting Review'), ('under_review', 'Under Review'), ('action_taken', 'Action Taken'), ('escalated', 'Escalated to FMC'), ('discharged', 'Discharged')], db_index=True, default='new', max_length=20)),
                ('opening_score', models.PositiveSmallIntegerField(blank=True, help_text='Risk score (0–100) when this record was created.', null=True)),
                ('latest_score', models.PositiveSmallIntegerField(blank=True, help_text='Most recent risk score — updated each time ML runs.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_advice_at', models.DateTimeField(blank=True, help_text='Timestamp of last lifestyle advice sent to patient.', null=True)),
                ('next_followup', models.DateField(blank=True, help_text='Date PHC staff scheduled a follow-up for this patient.', null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_to_case', models.OneToOneField(blank=True, help_text='The FMC PatientCase created when this record was escalated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phc_record', to='centers.patientcase')),
                ('hcc', models.ForeignKey(blank=True, help_text='The PHC managing this patient at the time this record was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_records', to='centers.healthcarecenter')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='phc_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PHC Patient Record',
                'verbose_name_plural': 'PHC Patient Records',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['patient', 'status'], name='centers_pat_patient_49d089_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['fhc', 'status'], name='centers_pat_fhc_id_a07de2_idx'),
        ),
        migrations.AddIndex(
            model_name='phcpatientrecord',
            index=models.Index(fields=['patient', 'status'], name='centers_phc_patient_271aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='phcpatientrecord',
            index=models.Index(fields=['hcc', 'status'], name='centers_phc_hcc_id_3eb780_idx'),
        ),
    ]
