# Generated by Django 6.0.3 on 2026-03-16 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('morning_time', models.CharField(default='08:00', max_length=5)),
                ('evening_time', models.CharField(default='20:00', max_length=5)),
                ('morning_checkin_enabled', models.BooleanField(default=True)),
                ('evening_checkin_enabled', models.BooleanField(default=True)),
                ('weekly_prompts_enabled', models.BooleanField(default=True)),
                ('period_alerts_enabled', models.BooleanField(default=True)),
                ('risk_score_updates_enabled', models.BooleanField(default=True)),
                ('wearable_sync_reminders', models.BooleanField(default=False)),
                ('do_not_disturb', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('behavioral_data_enabled', models.BooleanField(default=True)),
                ('wearable_data_enabled', models.BooleanField(default=True)),
                ('clinical_data_enabled', models.BooleanField(default=True)),
                ('share_with_clinician', models.BooleanField(default=True)),
                ('anonymized_research', models.BooleanField(default=False)),
                ('model_improvement', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Settings',
            },
        ),
        migrations.CreateModel(
            name='ConnectedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('apple_watch', 'Apple Watch'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('oura_ring', 'Oura Ring'), ('whoop', 'WHOOP')], max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_connected', models.BooleanField(default=True)),
                ('background_sync', models.BooleanField(default=True)),
                ('sync_frequency', models.CharField(choices=[('5min', 'Every 5 min'), ('15min', 'Every 15 min'), ('30min', 'Every 30 min'), ('1h', 'Every hour'), ('2h', 'Every 2 hours')], default='15min', max_length=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('data_quality_pct', models.PositiveSmallIntegerField(default=0)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connected Device',
                'unique_together': {('user', 'device_type')},
            },
        ),
    ]
