# Generated by Django 6.0.3 on 2026-03-16 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('white', 'White/Caucasian'), ('black', 'Black/African American'), ('hispanic', 'Hispanic/Latino'), ('asian', 'Asian'), ('south_asian', 'South Asian'), ('middle_eastern', 'Middle Eastern'), ('mixed', 'Mixed/Other'), ('prefer_not', 'Prefer not to say')], max_length=30)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('has_skin_changes', models.BooleanField(blank=True, null=True)),
                ('cycle_length_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('periods_per_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cycle_regularity', models.CharField(blank=True, choices=[('regular', 'Regular'), ('irregular', 'Irregular')], max_length=15)),
                ('selected_wearable', models.CharField(blank=True, choices=[('apple_watch', 'Apple Watch'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('oura_ring', 'Oura Ring'), ('none', 'None / Skip')], max_length=20)),
                ('rppg_baseline_captured', models.BooleanField(default=False)),
                ('rppg_captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Profile',
            },
        ),
    ]
