# Generated by Django 6.0.3 on 2026-03-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_federalhealthcenter_options_and_more'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprofile',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='registered_hcc',
            field=models.ForeignKey(blank=True, help_text="The Primary Health Centre this patient is registered with. Set during onboarding (patient picks from nearby PHCs filtered by state/LGA), or auto-set when PHC staff registers a walk-in patient. This is the patient's permanent home facility for Low/Moderate escalation routing.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='centers.healthcarecenter'),
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
