# Generated by Django 6.0.3 on 2026-03-17 02:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial — saved mid-session'), ('complete', 'Complete'), ('missed', 'Missed — window expired')], default='pending', max_length=10)),
                ('checkin_date', models.DateField(default=django.utils.timezone.localdate)),
                ('cycle_phase', models.CharField(choices=[('Menstrual', 'Menstrual'), ('Follicular', 'Follicular'), ('Ovulatory', 'Ovulatory'), ('Luteal', 'Luteal'), ('Unknown', 'Unknown')], default='Unknown', max_length=15)),
                ('cycle_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of menstrual cycle (1-35)', null=True)),
                ('hrv_sdnn_ms', models.FloatField(blank=True, help_text='SDNN in milliseconds from rPPG', null=True)),
                ('hrv_rmssd_ms', models.FloatField(blank=True, null=True)),
                ('hrv_captured_at', models.DateTimeField(blank=True, null=True)),
                ('hrv_skipped', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('missed_reminder_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-in Session',
                'verbose_name_plural': 'Check-in Sessions',
                'ordering': ['-checkin_date', 'period'],
            },
        ),
        migrations.CreateModel(
            name='CheckinStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_complete_date', models.DateField(blank=True, null=True)),
                ('total_days_logged', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-in Streak',
            },
        ),
        migrations.CreateModel(
            name='DailyCheckinSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_date', models.DateField(default=django.utils.timezone.localdate)),
                ('pelvic_pressure_vas', models.FloatField(blank=True, help_text='Pelvic_Pressure_VAS — from morning', null=True)),
                ('fatigue_mfi5_vas', models.FloatField(blank=True, help_text='Fatigue_MFI5_VAS — from morning', null=True)),
                ('painful_touch_vas', models.FloatField(blank=True, help_text='Painful_Touch_VAS — from morning PSQ-3', null=True)),
                ('breast_soreness_vas', models.FloatField(blank=True, help_text='Breast_Soreness_VAS — evening mastalgia normalised', null=True)),
                ('acne_severity_likert', models.FloatField(blank=True, help_text='Acne_Severity_Likert 0–3 from GAGS', null=True)),
                ('hirsutism_mfg_score', models.FloatField(blank=True, help_text='Hirsutism_mFG_Score — most recent mFG total', null=True)),
                ('bloating_delta_cm', models.FloatField(blank=True, help_text='Bloating_Delta_cm — evening', null=True)),
                ('cycle_phase', models.CharField(choices=[('Menstrual', 'Menstrual'), ('Follicular', 'Follicular'), ('Ovulatory', 'Ovulatory'), ('Luteal', 'Luteal'), ('Unknown', 'Unknown')], default='Unknown', max_length=15)),
                ('cycle_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hrv_sdnn_ms', models.FloatField(blank=True, null=True)),
                ('hrv_rmssd_ms', models.FloatField(blank=True, null=True)),
                ('unusual_bleeding', models.BooleanField(default=False)),
                ('morning_complete', models.BooleanField(default=False)),
                ('evening_complete', models.BooleanField(default=False)),
                ('prediction_run', models.BooleanField(default=False)),
                ('prediction_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evening_session', models.ForeignKey(blank=True, limit_choices_to={'period': 'evening'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evening_summary', to='health_checkin.checkinsession')),
                ('morning_session', models.ForeignKey(blank=True, limit_choices_to={'period': 'morning'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morning_summary', to='health_checkin.checkinsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Check-in Summary',
                'verbose_name_plural': 'Daily Check-in Summaries',
                'ordering': ['-summary_date'],
            },
        ),
        migrations.CreateModel(
            name='EveningCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breast_left_vas', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('breast_right_vas', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('mastalgia_side', models.CharField(blank=True, choices=[('Unilateral', 'Unilateral'), ('Bilateral', 'Bilateral')], max_length=12, null=True)),
                ('mastalgia_quality', models.CharField(blank=True, choices=[('Sharp', 'Sharp'), ('Dull', 'Dull'), ('Pressure', 'Pressure')], max_length=10, null=True)),
                ('breast_pain_avg', models.FloatField(blank=True, null=True)),
                ('cyclic_mastalgia_score', models.FloatField(blank=True, help_text='0–20, used as Breast_Soreness_VAS', null=True)),
                ('breast_soreness_vas', models.FloatField(blank=True, help_text='Normalised 0–10 for model', null=True)),
                ('mastalgia_severity', models.CharField(blank=True, choices=[('None', 'None'), ('Mild', 'Mild (avg ≤ 3.5)'), ('Moderate', 'Moderate (avg ≤ 7.0)'), ('Severe', 'Severe (avg > 7.0)')], max_length=10, null=True)),
                ('acne_forehead', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('acne_right_cheek', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('acne_left_cheek', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('acne_nose', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('acne_chin', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('acne_chest_back', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('gags_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('acne_severity_likert', models.FloatField(blank=True, help_text='0–3.0 normalised for model', null=True)),
                ('acne_severity_label', models.CharField(blank=True, choices=[('None', 'None (0)'), ('Mild', 'Mild (1–18)'), ('Moderate', 'Moderate (19–30)'), ('Severe', 'Severe (31–38)'), ('Very_Severe', 'Very Severe (>38)')], max_length=12, null=True)),
                ('bloating_delta_cm', models.FloatField(blank=True, help_text='Abdominal circumference Δ in cm', null=True)),
                ('unusual_bleeding', models.BooleanField(default=False, help_text='Any bleeding outside period window')),
                ('session', models.OneToOneField(limit_choices_to={'period': 'evening'}, on_delete=django.db.models.deletion.CASCADE, related_name='evening_data', to='health_checkin.checkinsession')),
            ],
            options={
                'verbose_name': 'Evening Check-in',
            },
        ),
        migrations.CreateModel(
            name='HirsutismMFGCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessed_date', models.DateField(default=django.utils.timezone.localdate)),
                ('mfg_upper_lip', models.PositiveSmallIntegerField(default=0, help_text='Upper lip', validators=[django.core.validators.MaxValueValidator(4)])),
                ('mfg_chin', models.PositiveSmallIntegerField(default=0, help_text='Chin', validators=[django.core.validators.MaxValueValidator(4)])),
                ('mfg_chest', models.PositiveSmallIntegerField(default=0, help_text='Chest', validators=[django.core.validators.MaxValueValidator(4)])),
                ('mfg_upper_back', models.PositiveSmallIntegerField(default=0, help_text='Upper back', validators=[django.core.validators.MaxValueValidator(4)])),
                ('mfg_lower_back', models.PositiveSmallIntegerField(default=0, help_text='Lower back', validators=[django.core.validators.MaxValueValidator(4)])),
                ('mfg_upper_abdomen', models.PositiveSmallIntegerField(default=0, help_text='Upper abdomen', validators=[django.core.validators.MaxValueValidator(4)])),
                ('mfg_lower_abdomen', models.PositiveSmallIntegerField(default=0, help_text='Lower abdomen', validators=[django.core.validators.MaxValueValidator(4)])),
                ('mfg_upper_arm', models.PositiveSmallIntegerField(default=0, help_text='Upper arm', validators=[django.core.validators.MaxValueValidator(4)])),
                ('mfg_thigh', models.PositiveSmallIntegerField(default=0, help_text='Thigh', validators=[django.core.validators.MaxValueValidator(4)])),
                ('mfg_total_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mfg_severity', models.CharField(blank=True, choices=[('Normal', 'Normal (0–7)'), ('Mild', 'Mild (8–16)'), ('Moderate', 'Moderate (17–24)'), ('Severe', 'Severe (≥25)')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfg_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hirsutism mFG Check-in',
                'verbose_name_plural': 'Hirsutism mFG Check-ins',
                'ordering': ['-assessed_date'],
            },
        ),
        migrations.CreateModel(
            name='MorningCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fatigue_vas', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('pelvic_pressure_vas', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('psq_skin_sensitivity', models.FloatField(blank=True, help_text='Q1: Skin sensitivity to light touch', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('psq_muscle_pressure_pain', models.FloatField(blank=True, help_text='Q2: Muscle pressure pain', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('psq_body_tenderness', models.FloatField(blank=True, help_text='Q3: Overall body tenderness', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('hyperalgesia_index', models.FloatField(blank=True, help_text='PSQ-3 mean (0–10) = Painful_Touch_VAS', null=True)),
                ('hyperalgesia_severity', models.CharField(blank=True, choices=[('Normal', 'Normal (0–3)'), ('Mild', 'Mild (3.01–6)'), ('Moderate', 'Moderate (6.01–9)'), ('Severe', 'Severe (9.01–10)')], max_length=10, null=True)),
                ('session', models.OneToOneField(limit_choices_to={'period': 'morning'}, on_delete=django.db.models.deletion.CASCADE, related_name='morning_data', to='health_checkin.checkinsession')),
            ],
            options={
                'verbose_name': 'Morning Check-in',
            },
        ),
        migrations.AddIndex(
            model_name='checkinsession',
            index=models.Index(fields=['user', 'checkin_date'], name='health_chec_user_id_3d7e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinsession',
            index=models.Index(fields=['user', 'status'], name='health_chec_user_id_6a3b05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkinsession',
            unique_together={('user', 'checkin_date', 'period')},
        ),
        migrations.AddIndex(
            model_name='dailycheckinsummary',
            index=models.Index(fields=['user', 'summary_date'], name='health_chec_user_id_a31d87_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycheckinsummary',
            index=models.Index(fields=['user', 'prediction_run'], name='health_chec_user_id_c9ed0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycheckinsummary',
            unique_together={('user', 'summary_date')},
        ),
        migrations.AlterUniqueTogether(
            name='hirsutismmfgcheckin',
            unique_together={('user', 'assessed_date')},
        ),
    ]
